sudo: required
language: go
go:
- "1.14.4"
go_import_path: github.com/dlespiau/kube-test-harness

jobs:
  include:
      - stage: build & unit tests
        script:
          - make dep
          - make lint
          - make unit-tests
      - stage: integration tests
        script:
          - make dep
          - .ci/setup-minikube v1.9.0
          - make integration-tests
